/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "app.h"
#include "foo.h"

std::string moving_source_files_does_not_affect_caching::Greeter::greeting() {
    return std::string("Hello, World!");
}

int main () {
    moving_source_files_does_not_affect_caching::Greeter greeter;
    std::cout << greeter.greeting() << std::endl;
    return 0;
}
